[build]
    timeout = 1200
    writeStats = true  # This is absolutely critical
    noJSConfigInAssets = true

    [build.buildStats]
      disableClasses = false
      disableIDs = true
      disableTags = true
      enable = true

    [[build.cachebusters]]
        source = 'assets/notwatching/hugo_stats\.json'
        target = 'css'

    [[build.cachebusters]]
      source = '(postcss|tailwind)\.config\.js'
      target = 'css'

[caches]
  [caches.assets]
      dir = ":cacheDir/assets"
      maxAge = -1

[module]
    [[module.mounts]]
        source = "assets"
        target = "assets"

    [[module.mounts]]
        source = "assets/svg/twemoji"
        target = "static/twemoji/svg"