baseURL = "https://ksvblog.site/"
defaultContentLanguage = 'my'
languageCode = "my"
languageName = "my"
theme = "ksv"
themesDir = "themes"
title = "K's V/Blog"

canonifyURLs = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
#relativeURLs = true
disableHugoGeneratorInject = false

[taxonomies]
author = 'authors'
category = 'categories'
series = 'series'
tag = 'tags'

[params]
author = "Hein Htet Kyaw"
description = "You can read Kiddo's Blogs again, Extra you can watch Video Tutorials later too."
facebook = "https://facebook.com/callmeHeinHtetKyaw"
github = "https://github.com/h2kyaw"
# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "G-MSGPDQ4L7R" # example: G-XXXXXXXXXX
image = "/images/og.png" 
ogimage = "/images/og.png" 
sitename = "K's V/Blog" 
twitter = "@HeinHtetKyaw_" 

[frontmatter]
date = ['date', 'publishdate', 'pubdate', 'published', 'lastmod', 'modified']
expiryDate = ['expirydate', 'unpublishdate']
lastmod = [':git', 'lastmod', 'modified', 'date', 'publishdate', 'pubdate', 'published']
publishDate = ['publishdate', 'pubdate', 'published', 'date']

[security]
enableInlineShortcodes = false
[security.exec]
allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$']
osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG)$']
[security.funcs]
getenv = ['^HUGO_', '^CI$']
[security.goTemplates]
allowActionJSTmpl = false
[security.http]
methods = ['(?i)GET|POST']
urls = ['.*']

[module]
[module.hugoVersion]
extended = false
min = "v0.95.0"

[[module.imports]]
path = "github.com/hugomods/shortcodes"
[[module.imports]]
path = "github.com/hugomods/mermaid"
[[module.imports]]
path = "github.com/hugomods/katex"
[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/search"
[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/site-verifications"
[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/pwa"
[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/gzip-caching"
# [[module.imports]]
# path = "github.com/jakejarvis/hugo-mod-twemoji"

[[module.mounts]]
source = 'content'
target = 'content'
[[module.mounts]]
source = 'static'
target = 'static'
[[module.mounts]]
source = 'layouts'
target = 'layouts'
[[module.mounts]]
source = 'data'
target = 'data'
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
source = 'i18n'
target = 'i18n'
[[module.mounts]]
source = 'archetypes'
target = 'archetypes'
[[module.mounts]]
source = 'static/uploads'
target = 'assets/uploads'

[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"

[build]
writeStats = true
[[build.cachebusters]]
source = "assets/watching/hugo_stats\\.json"
target = "main\\.css"
[[build.cachebusters]]
source = "(postcss|tailwind)\\.config\\.js"
target = "css"
[[build.cachebusters]]
source = "assets/.*\\.(js|ts|jsx|tsx)"
target = "js"
[[build.cachebusters]]
source = "assets/.*\\.(.*)$"
target = "$1"

[outputs]
home = ['html', 'rss', 'SearchIndex']
page = ['html']
rss = ['rss']
section = ['html', 'rss']
taxonomy = ['html', 'rss']
term = ['html', 'rss']

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
KaTeX = true
definitionList = true
footnote = true
linkify = true
linkifyProtocol = 'https'
strikethrough = true
table = true
taskList = true

[markup.goldmark.extensions.cjk]
eastAsianLineBreaks = false
enable = false
escapedSpace = false
[markup.goldmark.extensions.typographer]
apostrophe = '&rsquo;'
disable = false
ellipsis = '&hellip;'
emDash = '&mdash;'
enDash = '&ndash;'
leftAngleQuote = '&laquo;'
leftDoubleQuote = '&ldquo;'
leftSingleQuote = '&lsquo;'
rightAngleQuote = '&raquo;'
rightDoubleQuote = '&rdquo;'
rightSingleQuote = '&rsquo;'
[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = 'github'
wrapStandAloneImageWithinParagraph = true
[markup.goldmark.parser.attribute]
block = false
title = true
[markup.goldmark.renderer]
hardWraps = false
unsafe = false
xhtml = false

[params.katex]
enable = true
html_dom_element = "document.body"
[params.katex.mhchem]
enable = true
[params.katex.options]
errorColor = "#CD5C5C"
throwOnError = false

[[params.katex.options.delimiters]]
display = true
left = "$$"
right = "$$"
[[params.katex.options.delimiters]]
display = false
left = "$"
right = "$"
[[params.katex.options.delimiters]]
display = false
left = "\\("
right = "\\)"
[[params.katex.options.delimiters]]
display = true
left = "\\["
right = "\\]"

[params.markmap]
enable = true
[params.mermaid]
enable = true
theme = "neutral"
[params.mermaid.flowchart]
diagramPadding = 6

[outputFormats]
[outputFormats.SearchIndex]
baseName = "searchindex"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[deployment]
[[deployment.matchers]]
cacheControl = "max-age=31536000, no-transform, public"
gzip = true
pattern = "^.+\\.(js|css|svg|ttf)$"
[[deployment.matchers]]
cacheControl = "max-age=31536000, no-transform, public"
gzip = false
pattern = "^.+\\.(png|jpg)$"
[[deployment.matchers]]
contentType = "application/xml"
gzip = true
pattern = "^sitemap\\.xml$"
[[deployment.matchers]]
gzip = true
pattern = "^.+\\.(html|xml|json)$"
