title = "HHK BVlog"
baseURL = "https://hhk.my.id/"
publishDir = "public"
cacheDir = "/home/hhk/websites/id/.cache/hugo"

languageName = "မြန်မာ"
locale = "my-MM"
defaultContentLanguage = "my-mm"

canonifyURLs = false
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true

[caches]
    [caches.images]
        dir = ':cacheDir/images'

[imaging]
    resampleFilter = 'lanczos'
    [imaging.avif]
        compression = 'lossy'
        encoderSpeed = 10
        hint = 'photo'
        quality = 60
    [imaging.webp]
        compression = 'lossy'
        hint = 'photo'
        method = 4
        quality = 75
        useSharpYuv = true

[params]
    author = "Hein Htet Kyaw"
    authoremail = "mr.kiddomonster@gmail.com"
    keywords = "Hein Htet Kyaw, Hein Htet Kyaw blog, Hein Htet Kyaw vlog, software engineer, web developer, programming, technology, personal blog, Myanmar blogger"
    authorbio = "Hein Htet Kyaw is a software engineer and blogger. He is passionate about technology, programming, and sharing knowledge with others. He enjoys writing about various topics, including web development, software engineering, and personal experiences."

    google_tag_manager = "G-MSGPDQQ4L7R"
    gtm = "GTM-TRZM5JG9"

    sitename = "HHK BVlog"
    showVisitorLocation = true
    debug = false

    [params.icons]
        throw_on_error = false

[frontmatter]
    date = ['date', 'publishdate', 'pubdate', 'published', 'lastmod', 'modified']
    expiryDate = ['expirydate', 'unpublishdate']
    lastmod = ['lastmod', 'modified', 'date', 'publishdate', 'pubdate', 'published']
    publishDate = ['publishdate', 'pubdate', 'published', 'date']
