[[main]]
    Pre = 'about'
    Url = '/about'
    identifier = 'about'
    name = 'About'
    pageRef = '/about'
    weight = 1
[[main]]
    Pre = 'archive'
    Url = '/archive'
    identifier = 'archive'
    name = 'Archive'
    pageRef = '/archive'
    weight = 2
[[main]]
    Pre = 'work'
    Url = '/projects'
    identifier = 'projects'
    name = 'Projects'
    pageRef = '/projects'
    weight = 3
[[main]]
    Pre = 'books'
    Url = '/books'
    identifier = 'books'
    name = 'Books'
    pageRef = '/books'
    weight = 4
[[main]]
    Pre = 'blog'
    Url = '/articles'
    identifier = 'articles'
    name = 'Articles'
    pageRef = '/articles'
    weight = 5
[[main]]
    Pre = 'shop'
    Url = '/shop'
    identifier = 'shop'
    name = 'Shop'
    pageRef = '/shop'
    weight = 6
