[module]
    [module.hugoVersion]
        extended = true
        min = "v0.95.0"
[[imports]]
    path = "github.com/hugomods/mermaid"
[[imports]]
    path = "github.com/hugomods/katex"
[[imports]]
    path = "github.com/gethugothemes/hugo-modules/seo-tools/site-verifications"
[[imports]]
    path = "github.com/gethugothemes/hugo-modules/pwa"