[build]
    command = "./build.sh --baseURL $URL"
    publish = "public"
    timeout = 1200
    ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- assets/ config/ content/ data/ layouts/ static/ src/ cloudflare/ build.sh package.json package-lock.json netlify.toml"

[build.environment]
    HUGO_ENV = "production"

[context.production.environment]
    HUGO_ENABLEGITINFO = "false"

[context.split1]
    command = "./build.sh --baseURL $URL --enableGitInfo"

[context.split1.environment]
    HUGO_ENV = "production"

[context.deploy-preview]
    command = "./build.sh --buildFuture --baseURL $DEPLOY_PRIME_URL"

[context.branch-deploy]
    command = "./build.sh --baseURL $DEPLOY_PRIME_URL"

[context.next.environment]
    HUGO_ENABLEGITINFO = "false"

[[redirects]]
    from = "/npmjs/*"
    status = 200
    to = "/npmjs/"
